import { db } from "@dokploy/server/db";
import { domains } from "@dokploy/server/db/schema";
import type { Domain } from "@dokploy/server/services/domain";
import { eq } from "drizzle-orm";
import type { ApplicationNested } from "../builders";
import {
	getCaddyControllerLabels,
	updateCaddyControllerLabels,
} from "./application";
import { caddyLabelPrefix } from "./labels";

/**
 * Create path-related Caddy middlewares for a domain.
 *
 * For Caddy these are embedded in the domain's site block labels
 * (stripPrefix → `uri strip_prefix`, internalPath → `rewrite`).
 * Since the labels are already part of the domain labels generated by
 * `buildCaddyLabelsForDomain`, this function is a no-op for Caddy.
 *
 * It exists to keep the call-site branching symmetrical with Traefik.
 */
export const createCaddyPathMiddlewares = async (
	_app: ApplicationNested,
	_domain: Domain,
): Promise<void> => {
	// Path middlewares are embedded in the domain labels for Caddy.
};

/**
 * Remove path-related Caddy labels for a domain.
 *
 * Similar to createCaddyPathMiddlewares, the labels are removed as part
 * of `removeCaddyDomain`, so this is a no-op.
 */
export const removeCaddyPathMiddlewares = async (
	_app: ApplicationNested,
	_uniqueConfigKey: number,
): Promise<void> => {
	// Path middlewares are embedded in domain labels – removed together.
};

/**
 * Get all domains that belong to an application.
 */
const getApplicationDomains = async (applicationId: string) => {
	return db.query.domains.findMany({
		where: eq(domains.applicationId, applicationId),
	});
};

/**
 * Delete all Caddy middlewares (security + redirect) for an application.
 *
 * Removes labels from the Caddy controller that match the application's
 * security and redirect keys. Security labels use the pattern
 * `caddy_{domainKey}.basicauth[.{username}]` and redirect labels use
 * `caddy_{domainKey}.redir_{redirectKey}`.
 */
export const deleteAllCaddyMiddlewares = async (
	application: ApplicationNested,
): Promise<void> => {
	const { security, redirects, serverId } = application;

	if (security.length === 0 && redirects.length === 0) {
		return;
	}

	const labels = await getCaddyControllerLabels(serverId);
	const updated = { ...labels };
	const appDomains = await getApplicationDomains(application.applicationId);

	for (const domain of appDomains) {
		const domainKey = domain.uniqueConfigKey;

		// Remove security labels: caddy_{domainKey}.basicauth[.*]
		if (security.length > 0) {
			const secPrefix = `caddy_${domainKey}.basicauth`;
			for (const key of Object.keys(updated)) {
				if (key === secPrefix || key.startsWith(`${secPrefix}.`)) {
					delete updated[key];
				}
			}
		}

		// Remove redirect labels: caddy_{domainKey}.redir_{redirectKey}
		for (const redirect of redirects) {
			const redirKey = `caddy_${domainKey}.redir_${redirect.uniqueConfigKey}`;
			delete updated[redirKey];
		}
	}

	await updateCaddyControllerLabels(updated, serverId);
};
